sudo: false
language: node_js
node_js:
  - "6.10"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: Test Dogs
    - script: yarn run test-dogs
    - stage: Test Cats
    - script: yarn run test-cats
