sudo: false
language: node_js
node_js:
  - "6.10"
cache:
  directories:
  - node_modules
  yarn: true
jobs:
  include:
    - stage: test
    - script:
      - yarn run test-dogs
    - script:
      - yarn run test-cats
    - stage: deploy
    - script:
      - echo `date`

  stages:
    - Test
    - Deploy
